<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerL1pgpue\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerL1pgpue/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerL1pgpue.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerL1pgpue\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerL1pgpue\appDevDebugProjectContainer(array(
    'container.build_hash' => 'L1pgpue',
    'container.build_id' => '9549a42e',
    'container.build_time' => 1521454171,
));
