<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI8faqpo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI8faqpo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI8faqpo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI8faqpo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerI8faqpo\appDevDebugProjectContainer(array(
    'container.build_hash' => 'I8faqpo',
    'container.build_id' => 'e3c364ed',
    'container.build_time' => 1521451077,
));
